# Linear Regression with multiple variables

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_table('ex1data2.txt', sep=',', header=None, names=['size', 'number of bedrooms', 'price'], dtype=np.float32)
data

size  number of bedrooms     price
0   2104.0                 3.0  399900.0
1   1600.0                 3.0  329900.0
2   2400.0                 3.0  369000.0
3   1416.0                 2.0  232000.0
4   3000.0                 4.0  539900.0
5   1985.0                 4.0  299900.0
6   1534.0                 3.0  314900.0
7   1427.0                 3.0  198999.0
8   1380.0                 3.0  212000.0
9   1494.0                 3.0  242500.0
10  1940.0                 4.0  239999.0
11  2000.0                 3.0  347000.0
12  1890.0                 3.0  329999.0
13  4478.0                 5.0  699900.0
14  1268.0                 3.0  259900.0
15  2300.0                 4.0  449900.0
16  1320.0                 2.0  299900.0
17  1236.0                 3.0  199900.0
18  2609.0                 4.0  499998.0
19  3031.0                 4.0  599000.0
20  1767.0                 3.0  252900.0
21  1888.0                 2.0  255000.0
22  1604.0                 3.0  242900.0
23  1962.0                 4.0  259900.0
24  3890.0                 3.0  573900.0
25  1100.0                 3.0  249900.0
26  1458.0                 3.0  464500.0
27  2526.0                 3.0  469000.0
28  2200.0                 3.0  475000.0
29  2637.0                 3.0  299900.0
30  1839.0                 2.0  349900.0
31  1000.0                 1.0  169900.0
32  2040.0                 4.0  314900.0
33  3137.0                 3.0  579900.0
34  1811.0                 4.0  285900.0
35  1437.0                 3.0  249900.0
36  1239.0                 3.0  229900.0
37  2132.0                 4.0  345000.0
38  4215.0                 4.0  549000.0
39  2162.0                 4.0  287000.0
40  1664.0                 2.0  368500.0
41  2238.0                 3.0  329900.0
42  2567.0                 4.0  314000.0
43  1200.0                 3.0  299000.0
44   852.0                 2.0  179900.0
45  1852.0                 4.0  299900.0
46  1203.0                 3.0  239500.0

In [3]:
X = data.loc[:,['size','number of bedrooms']].values
Y = data.loc[:,['price']].values

In [4]:
mu = np.mean(X, axis=0)
sigma = np.std(X, axis=0)

X_train = (X-mu)/sigma
Y_train = Y

In [5]:
model = LinearRegression()

model.fit(X_train, Y_train.flatten()) 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
Y_pred = model.predict(X_train)
Y_pred

array([356283.1 , 286120.94, 397489.44, 269244.2 , 472277.8 , 330979.  ,
       276933.03, 262037.5 , 255494.6 , 271364.62, 324714.5 , 341805.2 ,
       326492.03, 669293.1 , 239903.  , 374830.34, 255879.98, 235448.25,
       417846.44, 476593.3 , 309369.12, 334951.62, 286677.78, 327777.16,
       604913.3 , 216515.61, 266353.03, 415030.  , 369647.3 , 430482.38,
       328130.3 , 220070.6 , 338635.6 , 500087.7 , 306756.34, 263429.6 ,
       235865.89, 351442.97, 641418.75, 355619.28, 303768.44, 374937.3 ,
       411999.6 , 230436.67, 190729.39, 312463.97, 230854.3 ],
      dtype=float32)

In [7]:
Y_train

array([[399900.],
       [329900.],
       [369000.],
       [232000.],
       [539900.],
       [299900.],
       [314900.],
       [198999.],
       [212000.],
       [242500.],
       [239999.],
       [347000.],
       [329999.],
       [699900.],
       [259900.],
       [449900.],
       [299900.],
       [199900.],
       [499998.],
       [599000.],
       [252900.],
       [255000.],
       [242900.],
       [259900.],
       [573900.],
       [249900.],
       [464500.],
       [469000.],
       [475000.],
       [299900.],
       [349900.],
       [169900.],
       [314900.],
       [579900.],
       [285900.],
       [249900.],
       [229900.],
       [345000.],
       [549000.],
       [287000.],
       [368500.],
       [329900.],
       [314000.],
       [299000.],
       [179900.],
       [299900.],
       [239500.]], dtype=float32)

In [8]:
mean_squared_error(Y_train, Y_pred)

4086560000.0

In [9]:
x = np.array([[1650, 3]])
x_norm = (x-mu)/sigma
model.predict(x_norm)

array([293081.46394551])